OtherEntitySuitEffect: false
#开启非玩家实体套装粒子特效 true(开)/false(关) 不建议开启
PROTECT_RUNE_JUDGE: "§a§l保护符: "
#保护符lore行识别符号，不冲突的情况下勿乱改
LEVEL_JUDGE: "§e§l淬炼属性: "
#属性lore行识别符号，不冲突的情况下勿乱改
MoveLevelInvTitle: "淬炼移星"
#移星界面标题
JudgeOffHand: true
#套装效果是否判断副手
DisplayNameFormat: 0
#淬炼后物品名称格式 0为不显示+等级 1为+等级显示在前 2为+等级显示在后
ReplaceLore:
#淬炼后删除包含以下字符串的lore
#    - "物理伤害"
#    - "魔法伤害"
#    - "火属伤害"
#    - "毒属伤害"
#    - "水属伤害"
#    - "风属伤害"
#    - "物理抗性"
#    - "魔法抗性"
#    - "火属抗性"
#    - "毒属抗性"
#    - "水属抗性"
#    - "风属抗性"
#    - "近战伤害"
#    - "AOE 伤害"
#    - "PVP 伤害"
#    - "PVE 伤害"
#    - "躲闪几率"
#    - "命中几率"
#    - "格挡几率"
#    - "格挡伤害"
#    - "暴击几率"
#    - "暴击伤害"
#    - "PVP 防御"
#    - "PVE 防御"
#    - "掉落加成"
#    - "移动速度"
#    - "耐久"
#    - "盔甲穿透"
#    - "吸血"
#    - "点燃几率"
#    - "攻击速度"
#    - "最大血量"
#    - "破血几率"
#    - "缴械几率"
#    - "攻击范围"